import { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body  style={{background: "linear-gradient(90deg, rgba(18,5,231,0.1292892156862745) 0%, rgba(0,0,0,0.09287464985994398) 14%, rgba(255,255,255,1) 25%, rgba(172,199,9,0.08167016806722693) 35%, rgba(230,40,8,0.05085784313725494) 59%, rgba(150,216,3,0) 81%, rgba(255,0,194,0.039653361344537785) 100%)"}}>
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
